import type { Component } from "vue";
import {
  Aim,
  Avatar,
  Bell,
  Calendar,
  ChatDotRound,
  CircleCheckFilled,
  Coin,
  Collection,
  Connection,
  Cpu,
  DataAnalysis,
  DataBoard,
  Document,
  Files,
  Flag,
  Folder,
  FolderOpened,
  Goods,
  Grid,
  HelpFilled,
  Histogram,
  HomeFilled,
  House,
  Key,
  List,
  Location,
  Lock,
  Management,
  Memo,
  Menu,
  Notebook,
  OfficeBuilding,
  Operation,
  Orange,
  Picture,
  PieChart,
  Platform,
  Postcard,
  Promotion,
  Reading,
  School,
  Search,
  Setting,
  Share,
  ShoppingCart,
  Star,
  Tickets,
  Tools,
  TrendCharts,
  User,
  UserFilled,
  WarningFilled,
} from "@element-plus/icons-vue";

type IconOption = { name: string; label: string; component: Component };

const iconEntries: [string, string, Component][] = [
  ["HomeFilled", "首页", HomeFilled], ["House", "门户", House],
  ["DataBoard", "数据看板", DataBoard], ["Grid", "应用", Grid],
  ["Menu", "菜单", Menu], ["List", "列表", List],
  ["UserFilled", "用户", UserFilled], ["User", "成员", User],
  ["Avatar", "个人", Avatar], ["Management", "管理", Management],
  ["OfficeBuilding", "组织", OfficeBuilding], ["School", "团队", School],
  ["Setting", "设置", Setting], ["Tools", "工具", Tools],
  ["Operation", "运营", Operation], ["Document", "文档", Document],
  ["Memo", "记录", Memo], ["Notebook", "笔记", Notebook],
  ["Collection", "收藏", Collection], ["Files", "文件", Files],
  ["Folder", "文件夹", Folder], ["FolderOpened", "打开文件夹", FolderOpened],
  ["Tickets", "工单", Tickets], ["Calendar", "日历", Calendar],
  ["Bell", "提醒", Bell], ["ChatDotRound", "消息", ChatDotRound],
  ["Search", "搜索", Search], ["Location", "位置", Location],
  ["Picture", "图片", Picture], ["Goods", "商品", Goods],
  ["ShoppingCart", "购物", ShoppingCart], ["Coin", "财务", Coin],
  ["TrendCharts", "趋势", TrendCharts], ["PieChart", "图表", PieChart],
  ["Histogram", "统计", Histogram], ["DataAnalysis", "分析", DataAnalysis],
  ["Promotion", "推广", Promotion], ["Platform", "平台", Platform],
  ["Connection", "连接", Connection], ["Share", "分享", Share],
  ["Cpu", "智能", Cpu], ["Reading", "阅读", Reading],
  ["Star", "星标", Star], ["Flag", "标记", Flag], ["Aim", "目标", Aim],
  ["Orange", "重点", Orange], ["Lock", "安全", Lock], ["Key", "密钥", Key],
  ["CircleCheckFilled", "完成", CircleCheckFilled],
  ["WarningFilled", "提醒", WarningFilled], ["HelpFilled", "帮助", HelpFilled],
  ["Postcard", "名片", Postcard],
];

export const elementPlusIconMap: Record<string, Component> = Object.fromEntries(
  iconEntries.map(([name, , component]) => [`el:${name}`, component]),
);

export const elementPlusMenuIcons: IconOption[] = iconEntries.map(
  ([name, label, component]) => ({ name: `el:${name}`, label, component }),
);
